import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FloatingNav from "@/components/ui/Navbar";

// ✅ Supabase imports
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import LoadingOverlay from "@/components/LoadingOverlay";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createServerComponentClient({ cookies });

  // ✅ Gọi session để kiểm tra đã kết nối chưa
  const {
    data: { session },
    error,
  } = await supabase.auth.getSession();

  // ✅ Log để kiểm tra
  console.log("Supabase session:", session);
  if (error) console.error("Supabase error:", error);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoadingOverlay />
        <Toaster/>
        {children}
      </body>
    </html>
  );
}
